### ISSUE TITLE
running app fails

### ISSUE THREAD

**Issue by neodark** [borenho/fiverr#1]
Hi,
Even after applying the migration, this error shows up:
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: fiverrapp_gig

**Comment by kaka-ruto** [comment]
Hey @neodark , thanks for pointing that out.
I have fixed it, the error was that at the homepage, we were trying to query the database for gigs and looping through the gigs, but then as a first time user, you won't be having gigs yet, so it throws an error.
To fix it, I just added an if statement to check if gigs are present, if they are, then show them, else show a message that there are no gigs yet.

**Comment by neodark** [comment]
@borenho looks like the workaround was not necessary, actually by just running python manage.py migrate --run-syncdb , it fixes this issue.
But still it's good you added it in case the --run-syncdb was not enforced.
